"""criei um novo campo

Revision ID: 2ba063441273
Revises: 6931d9f21468
Create Date: 2026-08-18 07:58:41.892998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba063441273'
down_revision: Union[str, Sequence[str], None] = '6931d9f21468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('eitxa', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'eitxa')
    # ### end Alembic commands ###
