"""adicionando a idade

Revision ID: 402797e5f04e
Revises: 2ba063441273
Create Date: 2026-08-18 08:02:58.231139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402797e5f04e'
down_revision: Union[str, Sequence[str], None] = '2ba063441273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('idae', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'idae')
    # ### end Alembic commands ###
