"""corrigir nullable

Revision ID: 4c87f76d98f7
Revises: a59f69b8769c
Create Date: 2026-09-28 17:24:27.604256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c87f76d98f7'
down_revision: Union[str, Sequence[str], None] = 'a59f69b8769c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historico_exames', 'arquivo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historico_exames', 'arquivo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
