"""apagar testes

Revision ID: 9f13dd42a007
Revises: 402797e5f04e
Create Date: 2026-08-18 08:05:19.163038

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f13dd42a007'
down_revision: Union[str, Sequence[str], None] = '402797e5f04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'eitxa')
    op.drop_column('users', 'idae')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('idae', sa.INTEGER(), nullable=False))
    op.add_column('users', sa.Column('eitxa', sa.VARCHAR(length=150), nullable=False))
    # ### end Alembic commands ###
