"""criar novas entidades e relacionamentos

Revision ID: a59f69b8769c
Revises: 9f13dd42a007
Create Date: 2026-09-28 17:23:36.733920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59f69b8769c'
down_revision: Union[str, Sequence[str], None] = '9f13dd42a007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Enum('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', name='days'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prontuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('sexo', sa.Enum('FEMININO', 'MASCULINO', name='sexotype'), nullable=True),
    sa.Column('tipo_sanguineo', sa.Enum('A_POSITIVO', 'A_NEGATIVO', 'B_POSITIVO', 'B_NEGATIVO', 'AB_POSITIVO', 'AB_NEGATIVO', 'O_POSITIVO', 'O_NEGATIVO', name='sanguetype'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('prontuario_id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('pressao', sa.Float(), nullable=True),
    sa.Column('diagnostico', sa.String(), nullable=True),
    sa.Column('sintomas', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'ATENDIDO', 'CANCELADO', name='statustype'), nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_exames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prontuario_id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescricoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prontuario_id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('exames', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescricao_medicamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prescricao_id', sa.Integer(), nullable=False),
    sa.Column('medicamento', sa.String(), nullable=False),
    sa.Column('via', sa.String(), nullable=False),
    sa.Column('posologia', sa.String(), nullable=False),
    sa.Column('duracao', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['prescricao_id'], ['prescricoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('doctors', sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='status'), nullable=False))
    op.add_column('users', sa.Column('tel', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cpf', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('street', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('cep', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cep')
    op.drop_column('users', 'number')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'street')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'cpf')
    op.drop_column('users', 'tel')
    op.drop_column('doctors', 'status')
    op.drop_table('prescricao_medicamentos')
    op.drop_table('prescricoes')
    op.drop_table('historico_exames')
    op.drop_table('consultas')
    op.drop_table('prontuarios')
    op.drop_table('agendas')
    # ### end Alembic commands ###
